# Build, test and pack the source code as a nuget.
# It's assumed that all source files reside in a directory 'src' inside the root of the repository.

name: Build, test & pack

on:
  workflow_call:
    inputs:
      configuration:
        description: 'Define whether this is a debug or a release build.'
        required: true
        type: string
      prerelease:
        description: 'Define if this is a prerelease.'
        required: true
        type: string
      suffix:
        description: 'Define the prerelease suffix, e.g. alpha.'
        required: true
        type: string
      publish_target:
        description: 'Define the publish target (None/nuget.org).'
        required: true
        type: string

defaults:
  run:
    working-directory: src

jobs:
  compute-version:
    uses: ./gitversion.yml
    with:
      prerelease: ${{ inputs.prerelease }}
      suffix: ${{ inputs.suffix }}


  build-and-pack:

    needs: compute-version
    runs-on: ubuntu-latest
    
    steps:      
    - uses: actions/checkout@v3
           
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c ${{ inputs.configuration }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal -c ${{ inputs.configuration }}
      
    - name: Pack
      run: dotnet pack --no-restore --no-build -o package_output -c ${{ inputs.configuration }} -p:PackageVersion=${{ needs.compute-version.outputs.package_version }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: src/package_output/*.nupkg
        
  publish:
    needs: build-and-pack
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./publish.yml
    with:
      target: ${{ inputs.publish_target }}
    secrets: inherit
