# Workflow to build and publish feaute/fix branches

name: Build on feature/fix branch

# Run on manual trigger only
on:
  workflow_call:

jobs:
  get-feature-branch:
  
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.normalize.outputs.branch_name }}
    
    steps:
    - uses: actions/checkout@v3
    
    # Remove feature/fix branch prefix, hyphens etc. and trim to 20 characters
    - name: Normalize branch name
      run: |
        branch="${{ github.ref_name }}"
        noSlashes=`echo $branch | sed "s/[^[:alnum:]]//g"`
        noFeature="${noSlashes/feature/}"
        noFix="${noFeature/fix/}"
        echo "::set-output name=branch_name::$( echo $noFix | cut -c 1-20 )"
      id: normalize

  feature-branch:
    needs: get-feature-branch
    uses: ./build-and-pack.yml
    with:
      configuration: "Debug"
      prerelease: "true"
      suffix: "alpha-${{ needs.get-feature-branch.outputs.branch_name }}"
      publish_target: "None"
    secrets: inherit
