# This workflow
# + builds and tests the develop branch,
# + can pack and upload a beta NuGet package
#
# This workflow must be called from other workflows.

name: Build, test & pack beta on develop

on:
  workflow_call:
    inputs:
      do_pack:
        description: 'If this build should be packed as NuGet package.'
        required: true
        type: boolean
      dotnet_version:
        description: 'The .NET SDK version that should be used by the runner (e.g. 6.0.x).'
        required: false
        type: string
        default: '6.0.x'

jobs:
  develop:
    uses: ./.github/workflows/build-and-pack.yml
    with:
      configuration: "Debug"
      do_pack: ${{ inputs.do_pack }}
      is_prerelease: true
      suffix: "beta"
      publish_target: "nuget.org"
      dotnet_version: ${{ inputs.dotnet_version }}
    # Pass on secrets to the next workflow.
    secrets: inherit
