# This workflow
# + builds and tests the chosen branch,
# + packs an alpha NuGet package
# + and stores the package as artifact.
#
# This workflow must be called from other workflows.

name: Build, test & pack beta on fix or feature branch

on:
  workflow_call:
    inputs:
      do_pack:
        description: 'If this build should be packed as NuGet package.'
        required: true
        type: boolean
      dotnet_version:
        description: 'The .NET SDK version that should be used by the runner (e.g. 6.0.x).'
        required: false
        type: string
        default: '6.0.x'

jobs:
  # Determines the feature branch name.
  get-feature-branch:
  
    runs-on: ubuntu-latest
    # Set the output for this job to make it accessible in the whole workflow.
    outputs:
      # Use the step with ID "normalize" and from the ouput with name "branch_name".
      branch_name: ${{ steps.normalize.outputs.branch_name }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Normalize branch name
      run: |
        # Take the branch name by GitHub variable "ref_name".
        branch="${{ github.ref_name }}"
        # Remove special characters.
        noSlashes=`echo $branch | sed "s/[^[:alnum:]]//g"`
        # Remove "/feature".
        noFeature="${noSlashes/feature/}"
        # Remove "/fix".
        noFix="${noFeature/fix/}"
        # Shorten name to 20 characters. Set it as output of the name "branch_name".
        echo "branch_name=$( echo $noFix | cut -c 1-20 )" >> $GITHUB_OUTPUT
      id: normalize

  feature-branch:
    # Requires the step above.
    needs: get-feature-branch
    # Run build-and-pack.yml.
    uses: ./.github/workflows/build-and-pack.yml
    with:
      configuration: "Debug"
      is_prerelease: true
      do_pack: ${{ inputs.do_pack }}
      # Needs.<job-name> gives access to the prior job's output.
      suffix: "alpha-${{ needs.get-feature-branch.outputs.branch_name }}"
      publish_target: "None"
      dotnet_version: ${{ inputs.dotnet_version }}
    # Pass on secrets to the next workflow.
    secrets: inherit
