# Compute nuget version using GitVersion.

name: GitVersion

on:
  workflow_call:
    inputs:
      is_prerelease:
        description: 'Define if this is a prerelease.'
        required: true
        type: boolean
      suffix:
        description: 'Define the prerelease suffix, e.g. alpha.'
        required: false
        type: string
        default: ""
    outputs:
      package_version:
        description: "Computed version for the package (SemVer)"
        value: ${{ jobs.nuget-version.outputs.version_output }}
        
defaults:
  run:
    working-directory: src
    
jobs:
  nuget-version:

    runs-on: ubuntu-latest
    outputs:
      version_output: ${{ steps.nuget_version.outputs.final_version }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Versioning
      id: gitversion
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "release/"
        format: "${major}.${minor}.${patch}"
        
    # Format is X.X.X-alpha000X-X, e.g. 8.1.0-alpha0008-42, where 0008 means 8 commits since last tag and 42 is the github run number.
    - name: Append prerelease suffix
      if: inputs.is_prerelease
      run: |
        echo "::set-output name=prerelease_suffix::-${{ inputs.suffix }}$(printf %4s ${{ steps.gitversion.outputs.increment }} | tr ' ' 0)-${{ github.run_number }}"
      id: prerelease_version
      
    - name: Output version
      run: |
           echo "::set-output name=final_version::${{ steps.gitversion.outputs.version }}${{ steps.prerelease_version.outputs.prerelease_suffix }}"
      id: nuget_version
